---
key: "ProductWriteES-1.0.0"
name : "ProductWriteES"
displayName : "ProductWriteES"
description: "Sample API"
version: "1.0.0"
serviceUrl: "https://{MI_HOST}:{MI_PORT}/product-write-es"
definitionType: "OAS3"
securityType: "BASIC"
mutualSSLEnabled: false
apiId : "null"
